### ISSUE TITLE
Make variables in BleScannerFragment public

### ISSUE THREAD

**Issue by JodliDev** [mbientlab/BleToolbox#1]
Hello
We want to implement a "connect to board when near phone" feature in our own app.
To be able to adjust for changes in your library in the future, we would like to stay as true as posible to
https://github.com/mbientlab/BleToolbox/blob/master/scanner/src/main/java/com/mbientlab/bletoolbox/scanner/BleScannerFragment.java

The problem is, that most variables in this class are private so we cant just extend to this class and change its inner workings.
But on the other hand, we cant just copy its source code and create our own version of this class because BleToolbox has no licence.

Is it possible to just make the variables "scannedDevicesAdapter" and "mHandler" public?
This way we could just have our own class like this:

```
public class Own_BleScannerFragment extends BleScannerFragment {
	@Override
	public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
		this.scannedDevicesAdapter = new OUR_OWN_CLASS(this.getActivity(), R.id.blescan_entry_layout);
		this.scannedDevicesAdapter.setNotifyOnChange(true);
		this.mHandler = new Handler();
		return inflater.inflate(layout, container);
	}	
}
```

Or, you could also introduce a new function like

```
public ScannedDeviceInfoAdapter create_scannedDeviceInfoAdapter() {
	return new ScannedDeviceInfoAdapter(getActivity(), R.id.blescan_entry_layout);
}
```
which is used in onCreateView().

Thank you very much! :)

**Comment by lkasso** [comment]
Is this still a thing or should I close it?

**Comment by lkasso** [comment]
closing. stale.
